### ISSUE TITLE
WidgetInstance.widget_class.choices is dynamic and causes django to expect migrations

### ISSUE THREAD

**Issue by rhysyngsun** [mitodl/open-widget-framework#24]
This line: https://github.com/mitodl/open-widget-framework/blob/master/open_widget_framework/open_widget_framework/models.py#L32

means that when we set `WIDGET_FRAMEWORK.WIDGET_CLASSES`, django expects a migration, so we need to instead configure choices at runtime instead of class definition time.

The open application checks for missing migrations and it can't write a new migration to the installed dependency (not that we'd want to).

Simply by adding this to the open `settings.py`:
```python
WIDGET_FRAMEWORK = {
    "WIDGET_CLASSES": ["open_discussions.widget_classes.MarkdownWidget"]
}
```
This ends up getting triggered:
```bash
mitodl@b9e3d5be28aa:/src$ ./manage.py makemigrations
Migrations for 'open_widget_framework':
  /usr/local/lib/python3.6/site-packages/open_widget_framework/migrations/0004_auto_20181129_1843.py
    - Alter field widget_class on widgetinstance
Traceback (most recent call last):
  File "./manage.py", line 14, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.6/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/base.py", line 316, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/base.py", line 353, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/base.py", line 83, in wrapped
    res = handle_func(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/commands/makemigrations.py", line 184, in handle
    self.write_migration_files(changes)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/commands/makemigrations.py", line 223, in write_migration_files
    with open(writer.path, "w", encoding='utf-8') as fh:
PermissionError: [Errno 13] Permission denied: '/usr/local/lib/python3.6/site-packages/open_widget_framework/migrations/0004_auto_20181129_1843.py'
```

**Comment by jklingen92** [comment]
Published the new version (0.2.13).

**Comment by rhysyngsun** [comment]
@jklingen92 I think you need to also generate a new migration for the removal of `choices` on the field, because I'm still seeing a migration needed:

```bash
mitodl@c3a97070750d:/src$ pip list | grep open-widget-framework
open-widget-framework   0.2.13     
mitodl@c3a97070750d:/src$ ./manage.py makemigrations --dry-run
Migrations for 'open_widget_framework':
  /usr/local/lib/python3.6/site-packages/open_widget_framework/migrations/0004_auto_20181130_1512.py
    - Alter field widget_class on widgetinstance
```

**Comment by jklingen92** [comment]
I removed choices from the most recent migration, so it should be good since choices isn't actually stored in the DB anywhere. Let me know if that goes through
